/**
 * AI Reasoning Panel
 *
 * Displays the AI's reasoning/thinking process during article generation.
 * Per Dec 18, 2025 meeting with Tony - provides transparency into AI decisions
 * to help debug issues and understand why AI made certain choices.
 *
 * Shows:
 * - Topic interpretation
 * - Contributor selection with alternatives considered
 * - Monetization category matching
 * - Internal link selection
 * - Data sources used
 * - Warnings and potential issues
 */

import { useState } from 'react'
import {
  Brain,
  ChevronDown,
  ChevronUp,
  AlertTriangle,
  User,
  Link,
  DollarSign,
  FileText,
  Database,
  Clock,
  CheckCircle,
  XCircle,
  Info,
  Lightbulb
} from 'lucide-react'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'

/**
 * Expandable section for reasoning categories
 */
function ReasoningSection({ title, icon: Icon, children, defaultExpanded = false, badge = null }) {
  const [expanded, setExpanded] = useState(defaultExpanded)

  return (
    <div className="border border-gray-200 rounded-lg overflow-hidden">
      <button
        onClick={() => setExpanded(!expanded)}
        className="w-full px-3 py-2 flex items-center justify-between bg-gray-50 hover:bg-gray-100 transition-colors"
      >
        <div className="flex items-center gap-2">
          <Icon className="w-4 h-4 text-purple-600" />
          <span className="text-sm font-medium text-gray-700">{title}</span>
          {badge}
        </div>
        {expanded ? (
          <ChevronUp className="w-4 h-4 text-gray-400" />
        ) : (
          <ChevronDown className="w-4 h-4 text-gray-400" />
        )}
      </button>
      {expanded && (
        <div className="p-3 border-t border-gray-200 bg-white">
          {children}
        </div>
      )}
    </div>
  )
}

/**
 * Warning item display
 */
function WarningItem({ warning }) {
  const severityColors = {
    low: 'bg-blue-50 text-blue-700 border-blue-200',
    medium: 'bg-yellow-50 text-yellow-700 border-yellow-200',
    high: 'bg-red-50 text-red-700 border-red-200',
  }

  const severityIcons = {
    low: Info,
    medium: AlertTriangle,
    high: XCircle,
  }

  const SeverityIcon = severityIcons[warning.severity] || AlertTriangle

  return (
    <div className={`p-2 rounded border ${severityColors[warning.severity] || severityColors.medium}`}>
      <div className="flex items-start gap-2">
        <SeverityIcon className="w-4 h-4 mt-0.5 flex-shrink-0" />
        <div className="flex-1 min-w-0">
          <p className="text-xs font-medium">{warning.type.replace(/_/g, ' ')}</p>
          <p className="text-xs mt-0.5">{warning.message}</p>
        </div>
      </div>
    </div>
  )
}

/**
 * Data source item display
 */
function DataSourceItem({ source }) {
  return (
    <div className="p-2 bg-gray-50 rounded border border-gray-200">
      <div className="flex items-start gap-2">
        <Database className="w-4 h-4 text-gray-500 mt-0.5 flex-shrink-0" />
        <div className="flex-1 min-w-0">
          <p className="text-xs font-medium text-gray-700">{source.source}</p>
          {source.entries_found && (
            <p className="text-xs text-gray-500">{source.entries_found} entries found</p>
          )}
          {source.freshness && (
            <p className="text-xs text-gray-500">Data from: {source.freshness}</p>
          )}
        </div>
      </div>
    </div>
  )
}

/**
 * Alternative contributor display
 */
function AlternativeContributor({ alt }) {
  return (
    <div className="p-2 bg-gray-50 rounded border border-gray-100">
      <div className="flex items-center justify-between">
        <span className="text-xs font-medium text-gray-700">{alt.name}</span>
        <Badge variant="outline" className="text-xs">
          Score: {alt.score}
        </Badge>
      </div>
      <p className="text-xs text-gray-500 mt-1">{alt.reason || 'No specific matches'}</p>
    </div>
  )
}

/**
 * Main AI Reasoning Panel Component
 */
export default function AIReasoningPanel({ reasoning, className = '' }) {
  const [showRawJson, setShowRawJson] = useState(false)

  // Handle case where no reasoning data exists
  if (!reasoning) {
    return (
      <div className={`p-4 bg-gray-50 rounded-lg border border-gray-200 ${className}`}>
        <div className="flex items-center gap-2 text-gray-500">
          <Brain className="w-5 h-5" />
          <div>
            <p className="text-sm font-medium">No AI Reasoning Available</p>
            <p className="text-xs mt-1">
              This article was created before reasoning tracking was enabled,
              or was not generated by the AI pipeline.
            </p>
          </div>
        </div>
      </div>
    )
  }

  const decisions = reasoning.decisions || {}
  const warnings = reasoning.warnings || []
  const dataSources = reasoning.data_sources || []

  return (
    <div className={`space-y-3 ${className}`}>
      {/* Header with metadata */}
      <div className="p-3 bg-purple-50 rounded-lg border border-purple-200">
        <div className="flex items-center gap-2 mb-2">
          <Brain className="w-5 h-5 text-purple-600" />
          <h3 className="font-medium text-purple-900">AI Reasoning Log</h3>
          {warnings.length > 0 && (
            <Badge variant="outline" className="bg-yellow-50 text-yellow-700 border-yellow-300">
              {warnings.length} warning{warnings.length !== 1 ? 's' : ''}
            </Badge>
          )}
        </div>

        <div className="flex flex-wrap gap-3 text-xs text-purple-700">
          {reasoning.model_used && (
            <div className="flex items-center gap-1">
              <Lightbulb className="w-3 h-3" />
              <span>Model: {reasoning.model_used}</span>
            </div>
          )}
          {reasoning.generated_at && (
            <div className="flex items-center gap-1">
              <Clock className="w-3 h-3" />
              <span>Generated: {new Date(reasoning.generated_at).toLocaleString()}</span>
            </div>
          )}
          {reasoning.temperature && (
            <span>Temp: {reasoning.temperature}</span>
          )}
        </div>
      </div>

      {/* Warnings Section (show first if any exist) */}
      {warnings.length > 0 && (
        <ReasoningSection
          title="Warnings & Issues"
          icon={AlertTriangle}
          defaultExpanded={true}
          badge={
            <Badge variant="outline" className="bg-yellow-50 text-yellow-700 border-yellow-300 text-xs">
              {warnings.length}
            </Badge>
          }
        >
          <div className="space-y-2">
            {warnings.map((warning, idx) => (
              <WarningItem key={idx} warning={warning} />
            ))}
          </div>
        </ReasoningSection>
      )}

      {/* Topic Interpretation */}
      {decisions.topic_interpretation && (
        <ReasoningSection title="Topic Interpretation" icon={FileText} defaultExpanded={true}>
          <div className="space-y-2 text-xs">
            <div>
              <span className="font-medium text-gray-500">Input Idea:</span>
              <p className="text-gray-800 mt-0.5">{decisions.topic_interpretation.input_idea}</p>
            </div>
            {decisions.topic_interpretation.description && (
              <div>
                <span className="font-medium text-gray-500">Description:</span>
                <p className="text-gray-800 mt-0.5">{decisions.topic_interpretation.description}</p>
              </div>
            )}
            <div>
              <span className="font-medium text-gray-500">Content Type:</span>
              <span className="ml-1 text-gray-800">{decisions.topic_interpretation.content_type}</span>
            </div>
            <div>
              <span className="font-medium text-gray-500">Target Word Count:</span>
              <span className="ml-1 text-gray-800">{decisions.topic_interpretation.target_word_count}</span>
            </div>
            {decisions.topic_interpretation.reasoning && (
              <div className="p-2 bg-purple-50 rounded border-l-2 border-purple-400">
                <p className="text-gray-700">{decisions.topic_interpretation.reasoning}</p>
              </div>
            )}
          </div>
        </ReasoningSection>
      )}

      {/* Contributor Selection */}
      {decisions.contributor_selection && (
        <ReasoningSection
          title="Author Selection"
          icon={User}
          badge={
            decisions.contributor_selection.selected && (
              <Badge variant="secondary" className="text-xs">
                {decisions.contributor_selection.selected}
              </Badge>
            )
          }
        >
          <div className="space-y-3 text-xs">
            {/* Selected contributor */}
            <div className="p-2 bg-green-50 rounded border border-green-200">
              <div className="flex items-center gap-2">
                <CheckCircle className="w-4 h-4 text-green-600" />
                <span className="font-medium text-green-800">
                  {decisions.contributor_selection.selected}
                </span>
                {decisions.contributor_selection.score !== undefined && (
                  <Badge className="bg-green-100 text-green-700 border-green-300">
                    Score: {decisions.contributor_selection.score}
                  </Badge>
                )}
              </div>
            </div>

            {/* Reasoning */}
            {decisions.contributor_selection.reasoning && (
              <div>
                <span className="font-medium text-gray-500">Why selected:</span>
                <p className="text-gray-700 mt-1 p-2 bg-gray-50 rounded">
                  {decisions.contributor_selection.reasoning}
                </p>
              </div>
            )}

            {/* Expertise match */}
            {decisions.contributor_selection.expertise_match?.length > 0 && (
              <div>
                <span className="font-medium text-gray-500">Expertise matches:</span>
                <div className="flex flex-wrap gap-1 mt-1">
                  {decisions.contributor_selection.expertise_match.map((exp, idx) => (
                    <Badge key={idx} variant="outline" className="text-xs">
                      {exp}
                    </Badge>
                  ))}
                </div>
              </div>
            )}

            {/* Alternatives considered */}
            {decisions.contributor_selection.alternatives_considered?.length > 0 && (
              <div>
                <span className="font-medium text-gray-500">Alternatives considered:</span>
                <div className="space-y-1 mt-2">
                  {decisions.contributor_selection.alternatives_considered.map((alt, idx) => (
                    <AlternativeContributor key={idx} alt={alt} />
                  ))}
                </div>
              </div>
            )}
          </div>
        </ReasoningSection>
      )}

      {/* Cost Data / Data Sources */}
      {(decisions.cost_data || dataSources.length > 0) && (
        <ReasoningSection
          title="Data Sources"
          icon={Database}
          badge={
            <Badge variant="outline" className="text-xs">
              {dataSources.length || (decisions.cost_data?.has_data ? 1 : 0)} source(s)
            </Badge>
          }
        >
          <div className="space-y-2">
            {decisions.cost_data && (
              <div className="text-xs">
                <div className="flex items-center gap-2 mb-2">
                  {decisions.cost_data.has_data ? (
                    <CheckCircle className="w-4 h-4 text-green-500" />
                  ) : (
                    <XCircle className="w-4 h-4 text-red-500" />
                  )}
                  <span className="font-medium">
                    Cost Data: {decisions.cost_data.has_data ? 'Found' : 'Not Available'}
                  </span>
                </div>
                {decisions.cost_data.entry_count && (
                  <p className="text-gray-600 ml-6">
                    {decisions.cost_data.entry_count} cost data entries available
                  </p>
                )}
                {decisions.cost_data.reasoning && (
                  <p className="text-gray-600 ml-6 mt-1">{decisions.cost_data.reasoning}</p>
                )}
              </div>
            )}

            {dataSources.map((source, idx) => (
              <DataSourceItem key={idx} source={source} />
            ))}
          </div>
        </ReasoningSection>
      )}

      {/* Monetization Category */}
      {decisions.monetization_category && (
        <ReasoningSection title="Monetization" icon={DollarSign}>
          <div className="space-y-2 text-xs">
            {decisions.monetization_category.selected && (
              <div className="p-2 bg-green-50 rounded border border-green-200">
                <p className="font-medium text-green-800">
                  Category: {decisions.monetization_category.selected.category}
                </p>
                {decisions.monetization_category.selected.concentration && (
                  <p className="text-green-700">
                    Concentration: {decisions.monetization_category.selected.concentration}
                  </p>
                )}
                {decisions.monetization_category.selected.level && (
                  <p className="text-green-700">
                    Level: {decisions.monetization_category.selected.level}
                  </p>
                )}
              </div>
            )}
            {decisions.monetization_category.reasoning && (
              <p className="text-gray-700 p-2 bg-gray-50 rounded">
                {decisions.monetization_category.reasoning}
              </p>
            )}
            {decisions.monetization_category.sponsored_count !== undefined && (
              <p className="text-gray-600">
                Sponsored schools available: {decisions.monetization_category.sponsored_count}
              </p>
            )}
          </div>
        </ReasoningSection>
      )}

      {/* Internal Links */}
      {decisions.internal_links && (
        <ReasoningSection
          title="Internal Links"
          icon={Link}
          badge={
            <Badge variant="outline" className="text-xs">
              {decisions.internal_links.links_added || decisions.internal_links.link_count || 0} links
            </Badge>
          }
        >
          <div className="space-y-2 text-xs">
            {decisions.internal_links.reasoning && (
              <p className="text-gray-700 p-2 bg-gray-50 rounded">
                {decisions.internal_links.reasoning}
              </p>
            )}
            {decisions.internal_links.selection_reasoning?.length > 0 && (
              <div className="space-y-2">
                {decisions.internal_links.selection_reasoning.map((link, idx) => (
                  <div key={idx} className="p-2 bg-blue-50 rounded border border-blue-100">
                    <p className="font-medium text-blue-800">{link.anchor || link.url}</p>
                    <p className="text-blue-600 text-xs">{link.url}</p>
                    <p className="text-gray-600 mt-1">{link.reason}</p>
                  </div>
                ))}
              </div>
            )}
          </div>
        </ReasoningSection>
      )}

      {/* Humanization */}
      {decisions.humanization && (
        <ReasoningSection title="Humanization" icon={Lightbulb}>
          <div className="space-y-2 text-xs">
            <p className="text-gray-700">
              <span className="font-medium">Provider:</span> {decisions.humanization.provider}
            </p>
            {decisions.humanization.mode && (
              <p className="text-gray-700">
                <span className="font-medium">Mode:</span> {decisions.humanization.mode}
              </p>
            )}
            {decisions.humanization.changes_made && (
              <p className="text-gray-700">
                <span className="font-medium">Changes:</span> {decisions.humanization.changes_made}
              </p>
            )}
            {decisions.humanization.ai_detection_score_before !== undefined && (
              <div className="flex items-center gap-4">
                <span>AI Detection: {decisions.humanization.ai_detection_score_before}%</span>
                <span>-&gt;</span>
                <span className="text-green-600 font-medium">
                  {decisions.humanization.ai_detection_score_after}%
                </span>
              </div>
            )}
          </div>
        </ReasoningSection>
      )}

      {/* Raw JSON Toggle */}
      <div className="pt-2 border-t border-gray-200">
        <Button
          variant="ghost"
          size="sm"
          onClick={() => setShowRawJson(!showRawJson)}
          className="text-xs text-gray-500 w-full"
        >
          {showRawJson ? 'Hide' : 'Show'} Raw JSON
        </Button>
        {showRawJson && (
          <pre className="mt-2 p-3 bg-gray-900 text-gray-100 rounded-lg text-xs overflow-auto max-h-60">
            {JSON.stringify(reasoning, null, 2)}
          </pre>
        )}
      </div>
    </div>
  )
}
