-- Seed monetization levels (degree levels for shortcodes)
INSERT INTO monetization_levels (level_name, level_code) VALUES
  ('Associate', 1),
  ('Bachelor', 2),
  ('Bachelor Completion', 3),
  ('Certificate', 6),
  ('Course', 399),
  ('Diploma', 7),
  ('Doctorate', 5),
  ('Graduate Certificate', 356),
  ('Graduate Course', 400),
  ('Master', 4),
  ('Post Graduate Certificate', 362),
  ('Professional Certificate', 393),
  ('Undergraduate Course', 401)
ON CONFLICT (level_code) DO NOTHING;

-- Seed monetization categories from GetEducated's degree database
-- This data is used to generate monetization shortcodes for articles

INSERT INTO monetization_categories (category, category_id, concentration, concentration_id) VALUES
  -- Arts & Liberal Arts (category_id: 8)
  ('Arts & Liberal Arts', 8, 'Anthropology', 285),
  ('Arts & Liberal Arts', 8, 'Art & Architecture (Architecture focus)', 18),
  ('Arts & Liberal Arts', 8, 'Digital Media Communications', 384),
  ('Arts & Liberal Arts', 8, 'English', 21),
  ('Arts & Liberal Arts', 8, 'Fashion & Interior Design', 22),
  ('Arts & Liberal Arts', 8, 'Foreign Language', 112),
  ('Arts & Liberal Arts', 8, 'Gender Studies', 305),
  ('Arts & Liberal Arts', 8, 'Graphic Design', 20),
  ('Arts & Liberal Arts', 8, 'History', 311),
  ('Arts & Liberal Arts', 8, 'Humanities', 23),
  ('Arts & Liberal Arts', 8, 'Liberal Arts', 24),
  ('Arts & Liberal Arts', 8, 'Journalism', 315),
  ('Arts & Liberal Arts', 8, 'Music', 25),
  ('Arts & Liberal Arts', 8, 'Political Science', 335),
  ('Arts & Liberal Arts', 8, 'Technical Writing', 349),
  ('Arts & Liberal Arts', 8, 'Writing', 27),

  -- Business (category_id: 9)
  ('Business', 9, 'Accounting', 281),
  ('Business', 9, 'Business Administration', 90),
  ('Business', 9, 'Business Analytics', 383),
  ('Business', 9, 'Business Management', 29),
  ('Business', 9, 'Communications', 30),
  ('Business', 9, 'Construction Management', 290),
  ('Business', 9, 'Digital Marketing', 33),
  ('Business', 9, 'Entrepreneurship', 41),
  ('Business', 9, 'Finance', 28),
  ('Business', 9, 'General Business', 357),
  ('Business', 9, 'Hospitality Management', 104),
  ('Business', 9, 'Human Resources', 35),
  ('Business', 9, 'International Business', 36),
  ('Business', 9, 'Management Information Systems', 31),
  ('Business', 9, 'Marketing', 37),
  ('Business', 9, 'Nonprofit Management', 328),
  ('Business', 9, 'Supply Chain Operations Management', 38),
  ('Business', 9, 'Organizational Leadership', 32),
  ('Business', 9, 'Project Management', 39),
  ('Business', 9, 'Public Administration', 337),
  ('Business', 9, 'Real Estate', 40),
  ('Business', 9, 'Sports Management', 42),
  ('Business', 9, 'Technology Management', 105),

  -- Computer Science & IT (category_id: 11)
  ('Computer Science & IT', 11, 'Computer Information Systems', 55),
  ('Computer Science & IT', 11, 'Information Technology', 56),
  ('Computer Science & IT', 11, 'IT Management', 58),
  ('Computer Science & IT', 11, 'Computer Science', 289),
  ('Computer Science & IT', 11, 'Database Administration', 53),
  ('Computer Science & IT', 11, 'Data Science', 387),
  ('Computer Science & IT', 11, 'Game Design', 54),
  ('Computer Science & IT', 11, 'GIS', 308),
  ('Computer Science & IT', 11, 'Information Security', 52),
  ('Computer Science & IT', 11, 'Network Administration', 354),
  ('Computer Science & IT', 11, 'Software Development', 275),
  ('Computer Science & IT', 11, 'Web Design & Development', 57),

  -- Criminal Justice, Safety & Law (category_id: 16)
  ('Criminal Justice, Safety & Law', 16, 'Administration', 379),
  ('Criminal Justice, Safety & Law', 16, 'Criminal Justice', 84),
  ('Criminal Justice, Safety & Law', 16, 'Cybersecurity', 293),
  ('Criminal Justice, Safety & Law', 16, 'Emergency Management', 296),
  ('Criminal Justice, Safety & Law', 16, 'Fire Science', 301),
  ('Criminal Justice, Safety & Law', 16, 'Forensic Science', 303),
  ('Criminal Justice, Safety & Law', 16, 'Homeland Security', 87),
  ('Criminal Justice, Safety & Law', 16, 'Law', 85),
  ('Criminal Justice, Safety & Law', 16, 'Law Enforcement', 380),
  ('Criminal Justice, Safety & Law', 16, 'Paralegal', 332),

  -- Education (category_id: 12)
  ('Education', 12, 'Adult Education', 364),
  ('Education', 12, 'Curriculum & Instruction', 292),
  ('Education', 12, 'Early Childhood Education', 61),
  ('Education', 12, 'Education Administration', 63),
  ('Education', 12, 'Educational Psychology', 385),
  ('Education', 12, 'Elementary Education', 60),
  ('Education', 12, 'ESL', 300),
  ('Education', 12, 'Family & Consumer Science', 365),
  ('Education', 12, 'General Education', 65),
  ('Education', 12, 'Gifted & Special Education', 62),
  ('Education', 12, 'Higher Education', 59),
  ('Education', 12, 'Instructional Design', 64),
  ('Education', 12, 'Library Science', 318),
  ('Education', 12, 'Physical Education & Coaching', 334),
  ('Education', 12, 'Reading & Literacy', 338),
  ('Education', 12, 'School Counseling', 340),
  ('Education', 12, 'Secondary Education (6-12)', 341),
  ('Education', 12, 'STEAM Education', 363),
  ('Education', 12, 'Teacher Leadership', 366),
  ('Education', 12, 'Teaching', 348),

  -- Engineering (category_id: 280)
  ('Engineering', 280, 'Aerospace Engineering', 283),
  ('Engineering', 280, 'Biomedical Engineering', 374),
  ('Engineering', 280, 'Chemical Engineering', 372),
  ('Engineering', 280, 'Civil Engineering', 287),
  ('Engineering', 280, 'Computer Engineering', 298),
  ('Engineering', 280, 'Electrical Engineering', 295),
  ('Engineering', 280, 'Engineering Management', 297),
  ('Engineering', 280, 'Environmental Engineering', 299),
  ('Engineering', 280, 'General Engineering', 306),
  ('Engineering', 280, 'Industrial Engineering', 313),
  ('Engineering', 280, 'Manufacturing Engineering', 375),
  ('Engineering', 280, 'Mechanical Engineering', 323),
  ('Engineering', 280, 'Nuclear Engineering', 373),
  ('Engineering', 280, 'Software Engineering', 344),
  ('Engineering', 280, 'Systems Engineering', 347),

  -- Healthcare (category_id: 14)
  ('Healthcare', 14, 'Dental Hygiene', 73),
  ('Healthcare', 14, 'General Healthcare', 361),
  ('Healthcare', 14, 'Gerontology', 307),
  ('Healthcare', 14, 'Health & Wellness', 360),
  ('Healthcare', 14, 'Health Informatics', 309),
  ('Healthcare', 14, 'Health Science', 310),
  ('Healthcare', 14, 'Healthcare Administration', 71),
  ('Healthcare', 14, 'Kinesiology', 358),
  ('Healthcare', 14, 'Medical Billing & Coding', 72),
  ('Healthcare', 14, 'Nutrition', 331),
  ('Healthcare', 14, 'Occupational Health & Safety', 367),
  ('Healthcare', 14, 'Pharmacy', 75),
  ('Healthcare', 14, 'Public Health', 77),
  ('Healthcare', 14, 'Radiology', 78),
  ('Healthcare', 14, 'Rehabilitation Therapies', 74),
  ('Healthcare', 14, 'Speech Language Pathology', 359),

  -- High School Diploma (category_id: 376)
  ('High School Diploma', 376, 'General', 377),
  ('High School Diploma', 376, 'Specialized', 378),

  -- Math & Science (category_id: 15)
  ('Math & Science', 15, 'Agriculture', 284),
  ('Math & Science', 15, 'Animal Science', 371),
  ('Math & Science', 15, 'Aviation', 368),
  ('Math & Science', 15, 'Biology', 369),
  ('Math & Science', 15, 'Biotechnology', 370),
  ('Math & Science', 15, 'Environmental Science', 81),
  ('Math & Science', 15, 'Forestry', 304),
  ('Math & Science', 15, 'Geography', 108),
  ('Math & Science', 15, 'Mathematics', 322),
  ('Math & Science', 15, 'Science', 83),
  ('Math & Science', 15, 'Sustainability', 346),

  -- Nursing (category_id: 13)
  ('Nursing', 13, 'Adult Gerontology (Nurse Practitioner)', 390),
  ('Nursing', 13, 'General Nursing', 69),
  ('Nursing', 13, 'Mental Health (Nurse Practitioner)', 389),
  ('Nursing', 13, 'MSN', 326),
  ('Nursing', 13, 'Neonatal & Pediatrics', 392),
  ('Nursing', 13, 'Nurse Educator', 329),
  ('Nursing', 13, 'Nursing Informatics', 388),
  ('Nursing', 13, 'Nurse Practitioner', 330),
  ('Nursing', 13, 'Nursing Administration', 68),
  ('Nursing', 13, 'RN to BSN', 67),
  ('Nursing', 13, 'RN to MSN', 355),
  ('Nursing', 13, 'Womens Health', 391),

  -- Psychology & Human Services (category_id: 278)
  ('Psychology & Human Services', 278, 'Behavioral Science', 386),
  ('Psychology & Human Services', 278, 'Counseling', 291),
  ('Psychology & Human Services', 278, 'Forensic Psychology', 302),
  ('Psychology & Human Services', 278, 'Human Services', 312),
  ('Psychology & Human Services', 278, 'Industrial Organizational Psychology', 314),
  ('Psychology & Human Services', 278, 'Marriage & Family Therapy', 321),
  ('Psychology & Human Services', 278, 'Psychology', 336),
  ('Psychology & Human Services', 278, 'Social Work', 342),
  ('Psychology & Human Services', 278, 'Sociology', 343),
  ('Psychology & Human Services', 278, 'Substance Abuse Counseling', 345),

  -- Religion & Philosophy (category_id: 279)
  ('Religion & Philosophy', 279, 'Biblical Studies', 382),
  ('Religion & Philosophy', 279, 'Divinity', 294),
  ('Religion & Philosophy', 279, 'Leadership & Ministry', 317),
  ('Religion & Philosophy', 279, 'Pastoral Counseling', 333),
  ('Religion & Philosophy', 279, 'Philosophy', 381),
  ('Religion & Philosophy', 279, 'Religion', 339),
  ('Religion & Philosophy', 279, 'Theology', 350),
  ('Religion & Philosophy', 279, 'Worship & Music Ministry', 327)
ON CONFLICT (category_id, concentration_id) DO NOTHING;
